[package]
name = "problem_50"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.7"
common = { path = "../common" }
itertools = "0.12.0"
